"""Add best_score to users

Revision ID: d585de454b7f
Revises: 0e48393758ca
Create Date: 2026-03-06 15:03:55.502857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd585de454b7f'
down_revision: Union[str, Sequence[str], None] = '0e48393758ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('best_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'best_score')
    op.alter_column('games', 'difficulty',
               existing_type=sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultystatus'),
               type_=postgresql.ENUM('EASY', 'MEDIUM', 'HARD', 'evil', name='difficultystatus_old'),
               existing_nullable=False)
    # ### end Alembic commands ###
